name: lidar_voxelnet
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - opencv
  - numba
  - matplotlib
  - scipy
  - pip
  - scikit-learn
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=12.1
  - pip:
    - shapely
    - easydict
    - Cython
